#!/bin/bash
#SBATCH -q batch   # job queue
#SBATCH -N 1       # number of nodes
#SBATCH -n 8       # number of cores
#SBATCH --mem 50G  # memory for all cores
#SBATCH -t 0-2:00  # time (D-HH:MM)

################################################################################
# Perform quality control on FASTQ files using FastQC.
# https://www.bioinformatics.babraham.ac.uk/projects/fastqc/
# 
# Your Name
# YYYY-MM-DD
################################################################################


### VARIABLES ###

# Full path to the FASTQ files.
FASTQ_DIR=/projects/baker-lab/rna/kzfp/fastqs

#Sample file prefix.
SAMPLE_PREFIX=SAMN122125

# Full path to the FastQC output directory.
OUTPUT_DIR=/projects/baker-lab/rna/kzfp/fastqc

# Full path to the FastQC container.
CONTAINER=/projects/baker-lab/rna/kzfp/fastqs/fastqc.sif

# List of sample file prefixes.
SAMPLES=(
    "RNA12_GT24-12486_ACTCCATC-GATCAAGG_S221_L008"
    "RNA14_GT24-12488_CGTGTGTA-CCAACGAA_S207_L008"
    "RNA8_GT24-12482_ACGTTCAG-AGTTGTGC_S218_L008"
    "RNA10_GT24-12484_TTGCAGAC-ATCGTGGT_S222_L008"
    "RNA15_GT24-12489_ACGACTTG-AACAGCGA_S202_L008"
    "RNA13_GT24-12487_GTTGACCT-CAGTGCTT_S198_L008"
    "RNA9_GT24-12483_CAGTCCAA-CGGTAATC_S223_L008"
    "RNA11_GT24-12485_CAATGTGG-TCTTCGAC_S216_L008"
    "RNA7_GT24-12481_AACGTCTG-AATGACGC_S204_L008"
)

### PROGRAM ###

# Load Singularity
module load singularity

# Explicity mount /flashscratch, /projects, and /data
export SINGULARITY_BIND="/projects/baker-lab"

# Run FastQC on FASTQ files.
for SAMPLE in "${SAMPLES[@]}"
do
    echo Processing Sample ${NUMBER}...
    
    SAMPLE=${SAMPLE_PREFIX}${NUMBER}
    
    singularity exec ${CONTAINER} fastqc --outdir ${OUTPUT_DIR} ${FASTQ_DIR}/${SAMPLE}_1.fastq.gz ${FASTQ_DIR}/${SAMPLE}_2.fastq.gz
done
